src/Entity/Users.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 5)]
    private ?string $zipCode = null;

    #[ORM\Column(length: 150)]
    private ?string $city = null;

    #[ORM\Column(type: 'boolean')]
    private $is_Verified = false;

    #[ORM\Column(type: 'string', length: 100)]
    private $reseToken;

    use CreatedAtTrait;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: Orders::class)]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->create_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

   public function getIsVerified() 
   {
       return $this->is_Verified;
   }

   public function setIsverified($is_Verified)
   {
      return $this->is_Verified = $is_Verified;
   }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUsers($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getReseToken()
    {
        return $this->reseToken;
    }

    /**
     * @param mixed $reseToken
     */
    public function setReseToken($reseToken): void
    {
        $this->reseToken = $reseToken;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUsers() === $this) {
                $order->setUsers(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Form\ResetPasswordFormType;
use App\Form\ResetPasswordRequestFormType;
use App\Repository\UsersRepository;
use App\Service\SendMailerService;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Exception\ORMException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {

        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    /**
     * @throws ORMException
     */
    #[Route(path: '/reset_pass', name: 'forgotten_pass')]

    public function forgottenPassword(
        Request $request,
        UsersRepository $usersRepository,
        TokenGeneratorInterface $tokenGenerator,
        EntityManagerInterface $em,
        SendMailerService $mailer
         ): Response
    {
        $resetpasswordForm = $this->createForm(ResetPasswordRequestFormType::class);

        $resetpasswordForm->handleRequest($request);

        if ($resetpasswordForm->isSubmitted() && $resetpasswordForm->isValid())
        {
            // get user by email
            $user = $usersRepository->findOneByEmail($resetpasswordForm->get('email')->getData());

            if ($user)
            {
                // on update user token
                $token = $tokenGenerator->generateToken();
                $user->setReseToken($token);
                $em->persist($user);
                $em->flush();
                // link for resetPass with neu Password
                $url =  $this->generateUrl('resetPass', ['token' => $token], UrlGeneratorInterface::ABSOLUTE_URL);

                // on crer email
                $context = compact('url', 'user');

                $mailer->send(
                    'replay@gmail.de',
                    $user->getEmail(),
                    'renitialisation pass pasword',
                    'resetPassword',
                    $context
                );

                $this->addFlash('success', 'email has been successfully sent');
                return $this->redirectToRoute('app_login');
            }

            $this->addFlash('danger', 'something wrong');
            return $this->redirectToRoute('app_login');
        }
        return $this->render('security/resetPasswordRequest.html.twig', [
            'resetPassword' => $resetpasswordForm->createView()
        ]);

    }

     #[Route(path: '/resetPass/{token}', name: 'resetPass')]
      public  function resetPass(
          $token,
         Request $request,
         UsersRepository $usersRepository,
         EntityManagerInterface $entityManager,
         UserPasswordHasherInterface $userPasswordHasher
     )
    {
        $user = $usersRepository->findOneByReseToken($token);
        
        if ($user) {
            
            $form = $this->createForm(ResetPasswordFormType::class);
            
             $form->handleRequest($request);
             
             if ($form->isSubmitted() && $form->isValid()) 
             {
                 $user->setReseToken('');
                 $user->setPassword(
                     $userPasswordHasher->hashPassword(
                         $user,
                         $form->get('password')->getData()
                     )
                 );

                 $entityManager->persist($user);
                 $entityManager->flush();
                 $this->addFlash('success', 'password has been changed');
                 return  $this->redirectToRoute('app_login');
             }


             return  $this->render('security/resetPassword.html.twig', [
                 'passwordForm' => $form->createView()
             ]);
        }

        $this->addFlash('danger', 'token invalid');
        return  $this->redirectToRoute('app_login');

    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}

<section class="container mt-4 " id="section">
    <div class="row h-100 d-flex align-items-center justify-content-center">
        <div class="col col-lg-6" >
            <form method="post" >
                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% if app.user %}
                    <div class="mb-3">
                        You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                    </div>
                {% endif %}

                <h1 class="h3 mb-3 font-weight-normal ">Anmelden</h1>
                <label for="inputEmail">Email</label>
                <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
                <label for="inputPassword">Password</label>
                <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

                <input type="hidden" name="_csrf_token"
                       value="{{ csrf_token('authenticate') }}"
                >
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" name="_remember_me"> Remember me
                        </label>
                    </div>

                <div class="btn-group-lg">
                    <button class="btn btn-lg btn-primary mb-5 mt-3" type="submit">Anmelden</button>
                    <a   href="{{ path('forgotten_pass') }}" class="btn btn-lg btn-primary mb-5 mt-3" type="submit">
                        Forgotten Password
                    </a>

                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/security/resetPassword.html.twig
{% extends 'base.html.twig' %}


{% block title %} Password reset{% endblock %}

{% block body %}
<section class="container my-3" id="section">
    <div class="row justify-content-center align-items-center align-content-center">
        <div class="col-4">

            <h1>Password reset</h1>
            {{ form_start(passwordForm) }}
            {{ form_row(passwordForm.password) }}
            <button type="submit" class="btn btn-primary">Submit</button>
            {{ form_end(passwordForm) }}

        </div>

    </div>

</section>
{% endblock %}

templates/security/resetPasswordRequest.html.twig
{% extends 'base.html.twig' %}


{% block title %}Password reset{% endblock %}

{% block body %}
<section class="container my-3" id="section">
    <div class="row justify-content-center align-content-center align-items-center">
        <div class="col-4">

            <h1>Password reset</h1>
            {{ form_start(resetPassword) }}
            {{ form_row(resetPassword.email) }}
            <button type="submit" class="btn btn-primary">Reset</button>
            {{ form_end(resetPassword) }}

        </div>

    </div>

</section>
{% endblock %}